### ISSUE TITLE
[Feature Request] 恳求加入对anki的支持

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [yan42685/obsidian-clever-search#10]
加上anki connect的支持，搜索anki卡片，在obsidian中显示，类似于https://github.com/aviral-batra/obsidian-power-search。
这个插件很好用，可惜暂停维护了，您看看能不能加上这个的支持，那就完美了，感谢您！

**Comment by shoudeyunkaijianyueming** [comment]
obsidian to anki制卡，利用您这个插件搜索，弥补obsidian块比较弱的缺点，真心希望您能考虑考虑

**Comment by yan42685** [comment]
适配 anki 有点超出本插件工作范围了...先观察一下，看有同样需求的人多不多吧。我还有一些疑问，虽然 power-search 没有维护了，但应该还能用吧；另外看你所说使用obsidian to anki制卡，那么数据也会在obsidian里面，Clever Search 可以搜到的呀

**Comment by shoudeyunkaijianyueming** [comment]
power search的确可以搜到，
1、但是对中文支持不太理想，
2、而且卡片过多的话，搜索就会一直转圈
3、obsidian的确可以搜到，但是它所搜到的是整个文档的部分，如果利用obsidian to anki制卡（标题等级制卡）的话，就可以利用power search 搜索到的话，就可以直接跳转到anki中，anki显示的是卡片，是该卡片部分，要比obsidian显示更好（整个文档和块（卡片）的区别
4、例外，power search可以对anki卡片自定义链接，可以应用在obsidain中，可以解决obsidian块连接不稳定的缺点

**Comment by shoudeyunkaijianyueming** [comment]
我不会编程，但希望能够尽量融合，如果您方便的话

**Comment by yan42685** [comment]
> power search的确可以搜到， 1、但是对中文支持不太理想，同时它是利用行内容搜索，而不是搜索文字 2、而且卡片过多的话，搜索就会一直转圈 3、obsidian的确可以搜到，但是它所搜到的是整个文档的部分，如果利用obsidian to anki制卡（标题等级制卡）的话，可以利用power search 搜索到anki卡片，利用卡片链接就可以直接跳转到anki中，anki显示的是卡片，是该卡片部分，要比obsidian显示更好（整个文档和块（卡片）的区别 4、例外，power search可以对anki卡片自定义链接，可以应用在obsidain中，可以解决obsidian块链接不稳定的缺点

你说的确实有道理，不过仔细考虑后我还是认为不合适：
1. 搜索插件的用户会使用anki功能的应该非常少，对于大多数用户来说这个整合是不必要的，还会拖慢插件加载速度；
2. 最终效果不一定能让你满意，因为存在两份数据，日常搜索结果会被污染的；
3. 整合anki需要对现有代码结构有较大的改动，为各种小众需求添加额外依赖会增加本插件后续维护难度，而我个人能力和精力十分有限，只能专注于大多数用户能用到的、对原有代码改动较小的需求

**Comment by shoudeyunkaijianyueming** [comment]
好的
