### ISSUE TITLE
[Feture Request] Inserting Link from Search Result Modal to Opened File

### ISSUE THREAD

**Issue by dolores824** [yan42685/obsidian-clever-search#13]
First off, just wanted to appreciate the great work on this plugin. It's incredibly convenient to use and smooths the searching. 

Just wondering would it be possible to insert link of the focused search result file into currently opened file directly while keeping the search modal opened. It could be super handy to insert multiple links from the search results into current document, making bi-directional referencing more efficient.

Thanks again for all the incredible work on this plugin!

**Comment by yan42685** [comment]
That sounds cool. Is there a third-party plugin that implements such a feature? I would appreciate a reference to make implementation easier.

**Comment by dolores824** [comment]
Thanks for your reply.

As far as I know, the [Another Quick Switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) plugin offers the feature of link insertion, as attached below:

<img src="https://github.com/yan42685/obsidian-clever-search/assets/33805669/139ce3f0-3737-499f-8ef3-c2f81a0e29b7" alt="image" width="500">


Hope it helps!

**Comment by yan42685** [comment]
This feature has been implemented at [0.2.1](https://github.com/yan42685/obsidian-clever-search/releases/tag/0.2.1). The information you provided saved me a lot of time, thanks.
