### ISSUE TITLE
[Feture Request] 是否可以支持 OB 的搜索语法？

### ISSUE THREAD

**Issue by Moyf** [yan42685/obsidian-clever-search#14]
## Please describe your idea concisely
比如现在搜索 `pr`，会把 `promise` 之类的单词也搜索进去；
能不能用 `"pr"` 来设定 **全字匹配**，在这个情况下只检索 `pr` 这个词，而忽略其他的 `pr...` 开头的词？

另外还有像是 `line()` 之类的限定词，只搜索出现在同一行/同一段内的情况，能更好地控制搜索范围

## Screenshots
![image](https://github.com/yan42685/obsidian-clever-search/assets/4013062/ebc8597a-d599-4bdb-aa67-089a643c7f0d)

**Comment by yan42685** [comment]
精确匹配词语可以实现，后面的line语法似乎并非必要，出现多个不同匹配词的文件和行会优先排在前面。

另外，近期空闲时间很少，只能以后再实现了

**Comment by Moyf** [comment]
> 精确匹配词语可以实现，后面的line语法似乎并非必要，出现多个不同匹配词的行会优先排在前面。
> 
> 另外，近期空闲时间很少，只能以后再实现了

（希望能支持一下精确匹配词语，恰好最近又碰到这个需求了 > <

**Comment by yan42685** [comment]
我研究了下，实现精确匹配困难重重且效果不好。本插件所使用的BM25算法库Minisearch的作者未支持精确匹配功能：
![image](https://github.com/user-attachments/assets/3c2ab62f-9d8c-49ce-ac9c-608d504abbd4)
所以只能在模糊匹配后，读取所有候选文件并进行全文匹配、过滤掉不包含精确匹配词的文件。如果候选文件大于20个，延迟就很明显了；对于大的库可能有几百上千个候选项，那得等十几秒出结果...此外改起来也有点麻烦，会产生不少相似代码。

对于你的场景来说，“输入-np 本次搜索取消前缀匹配”这样的功能够用吗？比如像这样
![image](https://github.com/user-attachments/assets/5c0846e6-fab2-4e96-b1b0-60c466af84e9)

**Comment by Moyf** [comment]
> I did some research, and achieving exact matching is difficult and ineffective. The author of Minisearch, the BM25 algorithm library used by this plug-in, does not support the exact matching function: [lucaong/minisearch#216](https://github.com/lucaong /minisearch/issues/216) ![image](https:// private-user-images.githubusercontent.com/41834091/380149701-3c2ab62f-9d8c-49ce-ac9c-608d504abbd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp XVCJ9..GkoFjxUyhhGaVCY8-P83gn 8mWYuSb5v -AAUNXLio-H8) so it can only be read after fuzzy matching All candidate files are matched in full text and files that do not contain exact matching words are filtered out. If there are more than 20 candidate files, the delay will be obvious; for large libraries, Image may contain: text that says '... In addition, it is a bit troublesome to change, and a lot of similar code will be generated.
>
> For your scenario, enter /np. Is the function "cancel prefix matching for this search" available? For example: ![image](https://private-user-images.githubusercontent.com/41834091/ 380157952-5C0846E6-FAB2-4E96-B1B0-60C466AF84E9.PNG? JWT = EYJHBGCIOJIUZIISINR5CCI6IKPXVCJ9..rv9ECSAYB66-WVQD4GGPO0ICHBCS0FFFFFF Adiyaqznyvbq)
>
> The results of searching pr when prefix matching is not canceled are indeed not good enough: ![image](https://private-user-images.githubusercontent.com/41834091/380158777-2a00ceca-2aa8-4936-9d 25-a5ae0d6a3902.png? jwt =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..AFkOTdHo0pDsBrX40qW8qKqPrL4XzvixdnSpHjpSah4)

Ah, so that’s it… It’s really hard to support.

I think this feature you mentioned (cancel prefix matching) can also solve the problems I encountered to a great extent! Like PR/Promise and> 我研究了下，实现精确匹配困难重重且效果不好。本插件所使用的BM25算法库Minisearch的作者未支持精确匹配功能： [lucaong/minisearch#216](https://github.com/lucaong /minisearch/issues/216) ![image](https://private-user-images.githubusercontent.com/41834091/380149701-3c2ab62f-9d8c-49ce-ac9c-608d504abbd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp XVCJ9..GkoFjxUyhhGaVCY8-P83gn8mWYuSb5v -AAUNXLio-H8) 所以只能在模糊匹配后，读取所有候选文件并进行全文匹配、过滤掉不包含精确匹配词的文件。如果候选文件大于20个，延迟就很明显了；对于大的库Image may contain: text that says '...此外改起来也有点麻烦，会产生不少相似代码。
>
> 对于你的场景来说，输入/np 本次搜索取消前缀匹配”这样的功能够用吗？比如这样： ![image](https://priv ate-user-images.githubusercontent.com/41834091/ 380157952-5c0846e6-fab2-4e96-b1b0-60c466af84e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..RV9EcsaYB66-WVQD4ggpo0iCHBcs0FFAdiYAqznYvbQ )
>
> 未取消前缀匹配时搜索pr的结果确实不够好： ![image](https://private-user-images.githubusercontent.com/41834091/380158777-2a00ceca-2aa8-4936-9d 25-a5ae0d6a3902.png?jwt =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..AFkOTdHo0pDsBrX40qW8qKqPrL4XzvixdnSpHjpSah4)

啊，原来是这样……那支持起来确实好折腾了。

我觉得你说的这个特性（取消前缀匹配）也能很大程度上解决我所遇到的问题！像是 PR/Promise 还有 Wind/Windows 之类的情况。

如果做的话，是否可以支持自定义 `/np` 关键字 + 支持在设置里直接配置全局的「是否前缀匹配」开关？

（话说顺便问一下，大小写匹配麻烦吗？）

**Comment by yan42685** [comment]
今天有点空，都实现了，看看有什么问题吗

**Comment by Moyf** [comment]
嗯，我这边更新试了一下：
1. `/np PR` 取消前缀匹配：✅
2. 设置里的前缀匹配开关：✅
3. 设置里的大小写匹配：✅

这几个都没问题！

（然后自定义 `/np` 关键字的设置没找到——不过也不关键，这个输入一下还挺快的；测试的时候发现是只能放在检索词的最前面对吗？比如只能用 `/np PR`，不能用 `PR /np` 🤔

**Comment by yan42685** [comment]
目前是只能放在检索内容前面，以后有空了改成前面或后面吧，筛选式命令很符合直觉；没有实现“自定义命令的名字“；在readme还有其他的命令介绍

**Comment by yan42685** [comment]
0.2.13 支持命令放在输入框末尾了，需要用一个空格隔开

**Comment by Moyf** [comment]
> 目前是只能放在检索内容前面，以后有空了改成前面或后面吧，筛选式命令很符合直觉；没有实现“自定义命令的名字“；在 README 还有其他的命令介绍

嗯嗯，明白了，感谢~

**Comment by Moyf** [comment]
> 0.2.13 支持命令放在输入框末尾了，需要用一个空格隔开

好耶！太棒嘞~ 🥳
