### ISSUE TITLE
装上插件Obsidian就黑屏

### ISSUE THREAD

**Issue by chliuhq** [yan42685/obsidian-clever-search#19]
刚装上插件还是好的，点开设置就黑屏了。重启Obsidian后提示在检索，可能卡顿。稍等不到一分钟Obsidian便黑屏。

![image](https://github.com/yan42685/obsidian-clever-search/assets/38576927/21a23fd4-4b91-41b7-af66-0402138b9da5)

## Environment
 - OS: Windows 11
 - Obsidian Version: v1.5.3
 - Plugin Version:最新版

**Comment by yan42685** [comment]
有使用excalidraw插件吗

**Comment by chliuhq** [comment]
> 有使用excalidraw插件吗

这么快就回复了！
有的，刚才我关上excalidraw后还是黑屏。

**Comment by yan42685** [comment]
以前有用户反馈过和excalidraw冲突的问题，原因应该是把excalidraw的某些文件当成markdown索引了，所以关闭excalidraw也无效，需要做的是在 设置-文件与链接 把存放excalidraw文件的目录排除

**Comment by chliuhq** [comment]
可能还有其他插件也会影响。
我把excalidraw数据文件夹和插件文件夹都删掉了还是会黑屏

**Comment by yan42685** [comment]
方便qq远程桌面吗，我尝试排查一下原因
