### ISSUE TITLE
通过bart配置插件后不显示搜索框

### ISSUE THREAD

**Issue by cloudchildrens** [yan42685/obsidian-clever-search#26]
![image](https://github.com/user-attachments/assets/e70e12fa-ea2c-495e-98f0-5f4a79e391b4)

索引完成后，为什么没有搜索框？

**Comment by yan42685** [comment]
索引后不会自动打开搜索框，需要通过命令search in vault semantically 打开

**Comment by cloudchildrens** [comment]
> 索引后不会自动打开搜索框，需要通过命令search in vault semantically 打开

解决了！
