### ISSUE TITLE
[BUG] Search for XSS vulnerabilities in the vault  

### ISSUE THREAD

**Issue by UzJu** [yan42685/obsidian-clever-search#28]
# # Description error
Briefly describe the mistakes.

<！ -only open the community plug-in in the new vault to reproduce->
# # Reproduction step
1. Go to " ...
Create a new md file and then write the following characters.
```
echo '<img src=https://crowdshield.com/.testing/xss.js onload=prompt(2) onerror=alert(3)></img>'// XXXXXXXXXX
```
2. Click' ...' 3.
Then use the function of search in vault.
3. Scroll down to " ....
4. Check the errors
<img width="1289" alt="image" src="https://github.com/user-attachments/assets/6e48592e-f7f2-406c-922d-d7a1caf461aa">
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/a9580e98-1225-4926-806c-8888686aadf5">

# # Expected behavior
Briefly describe what you expect to happen.

<！ -optional->
# # screenshot
If applicable, please add screenshots to help explain your problem.

# # Environment
- OS：
- Obsidian Version：
-Plug-in version: latest

**Comment by yan42685** [comment]
Thanks for reminding me. I'll cope with it this week.

**Comment by yan42685** [comment]
Fixed in [2.1.1](https://github.com/yan42685/obsidian-clever-search/releases/tag/0.2.11) 😃

**Comment by yan42685** [comment]
I wonder if it's necessary for clever-search to address this issue. After all, it seems that Obsidian has no measures against XSS, and opening a note with harmful code already puts you in danger.

**Comment by UzJu** [comment]
Hello:)  Thanks again for such a great plugin for Obsidian, I've re-tested the fix version and the issue has been fixed, no new issues found.

It's ok, because my main job is security research, I have some attack payloads inside my notes, and then one time I queried it, I triggered the issue by chance, so I'll give you the first feedback.

Thanks again for such a great plugin and have a nice life!

**Comment by yan42685** [comment]
Hello! I'm glad to know you recognize the value of this plugin, and I appreciate your feedback. If you need anything in the future, feel free to reach out. Wishing you all the best in your security research. Have a wonderful weekend!
