### ISSUE TITLE
[Feature Request] 能否支持对搜索的结构直接进行复制，以及鼠标双击跳转

### ISSUE THREAD

**Issue by PandaNocturne** [yan42685/obsidian-clever-search#6]
### 能否支持对搜索的结构直接进行复制？

我目前相对搜索的结果进行复制，发现并不能选中文本，我并不追求能够编辑，但是希望可以有时间能够直接复制一些搜索结果，这样会不会稍微便捷一点
![image](https://github.com/yan42685/obsidian-clever-search/assets/84729049/67fa652a-15d2-4e1d-87d8-a2f22467b2c3)

### 能否鼠标双击跳转

每次跳转搜索页面时，对我这个有时喜欢鼠标点点点的人来说，双击并不能跳转，要特别按下回车，当然只是个人习惯，大大你看着改就行

**Comment by yan42685** [comment]
右键可以跳转的，复制的话，左键双击的时候复制当前行吗？

**Comment by yan42685** [comment]
选中文本这个应该不行，svelte 渲染的 html，没法用程序改动

**Comment by PandaNocturne** [comment]
> 右键可以跳转的，复制的话，左键双击的时候复制当前行吗？

哦哦 我不知道鼠标右键可以跳转，原来如此，我知道，复制的功能其实不是太重要的，谢谢大大

**Comment by yan42685** [comment]
> > 右键可以跳转的，复制的话，左键双击的时候复制当前行吗？
> 
> 哦哦 我不知道鼠标右键可以跳转，原来如此，我知道，复制的功能其实不是太重要的，谢谢大大

没事，你习惯右键跳转吗？我没有立刻考虑加上左键双击跳转，是因为，跳转占用了两种鼠标点击方式，丢失了拓展的可能性，比如说加强版预览：渲染markdown（现在的纯文本只能看到图片链接）

然后把右键改成左键双击的话，之前有些用户习惯了右键，可能又不习惯左键双击了

**Comment by PandaNocturne** [comment]
右键跳转，知道就还好，问题不大，我一开始是不知道右键跳转的，所以习惯性用双击了

**Comment by yan42685** [comment]
嗯好

**Comment by PandaNocturne** [comment]
> 嗯好

才发现文档里面写了，是我鲁莽了，真是打扰了😅

**Comment by yan42685** [comment]
哈哈，没事的，等我下一个主要功能做出来，帮忙宣传一下呗，（是我没接触过的领域，还不清楚技术难度如何）

**Comment by PandaNocturne** [comment]
> 哈哈，没事的，等我下一个主要功能做出来，帮忙宣传一下呗，（是我没接触过的领域，还不清楚技术难度如何）

哈哈哈 没问题，非常棒的搜索插件，已经是必备插件之一了，肯定会多多推荐的

**Comment by yan42685** [comment]
复制功能已实现，之前是因为和保持输入框焦点冲突了
