### ISSUE TITLE
[Feture Request]  全局搜索跳转到文档时，设置当前文档的模式为实时预览

### ISSUE THREAD

**Issue by calmwaves111** [yan42685/obsidian-clever-search#7]
我在Obsidian中的设置是这样的
![image](https://github.com/yan42685/obsidian-clever-search/assets/56907077/09ea8fba-7cd6-40b5-93ad-8288413f3c1b)
因此当我按下enter，然后进入文档时，尽管光标已经设定在了目标所在行，但是我的文档模式还是阅读视图，我必须切换到实时预览
我希望能先强制让文档视图转为实时预览
下面是一些可能有用的参考代码
```
        const view = app.workspace.activeLeaf.getViewState();
        view.state.mode = "source";
        view.state.source = true;
        app.workspace.activeLeaf.setViewState(view);
```

**Comment by yan42685** [comment]
虽然这段代码不能直接使用，但给了我很有用的提示，需要用 obsidian 新提供的api来实现，预计明天可以先把 main.js 发给你，没有 bug 要改的话，暂时不发布新版本了，最近 release 得有点频繁。

最后补充一下，根据官方文档，如果你在其他代码里使用了这样的API，以后可能会失效噢。

https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines
![image](https://github.com/yan42685/obsidian-clever-search/assets/41834091/222f865c-77e2-4adf-ac50-a1f09d07724d)
![image](https://github.com/yan42685/obsidian-clever-search/assets/41834091/b75387ac-8e81-4ddf-8cf2-124fd46e99c0)

**Comment by calmwaves111** [comment]
或许可以切换到实时预览，现在切换到的是源码模式
那段代码我也是从这个帖子里抄的，应该把`view.state.source`改成false就行
https://forum.obsidian.md/t/easily-switch-between-source-mode-live-preview-preview/27151/14

**Comment by yan42685** [comment]
> 或许可以切换到实时预览，现在切换到的是源码模式 那段代码我也是从这个帖子里抄的，应该把`view.state.source`改成false就行 https://forum.obsidian.md/t/easily-switch-between-source-mode-live-preview-preview/27151/14

感谢提醒，是我疏忽了哈哈，已经在 0.1.7 改成实时预览模式了
