### ISSUE TITLE
[Question] Omnisearch似乎对中文分词支持不好

### ISSUE THREAD

**Issue by Zacharia2** [yan42685/obsidian-clever-search#8]
可以加入Omnisearch推荐的分词库嘛？或者增强中文分词。

**Comment by yan42685** [comment]
用的是和Omnisearch一样的结巴分词，只是处理方式不一样。Omnisearch是另一个插件，我没法大幅修改噢。

**Comment by Zacharia2** [comment]
哦哦哦，谢谢谢谢谢。原来是我看错了。
